app = "english-learning-bot"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  TELEGRAM_TOKEN="7886795344:AAG5_JT5Mi2OPhNUfGS5-bW-pFaGPprXeAY"

[mounts]
  source = "bot_data"
  destination = "/app/audio"
